### ISSUE TITLE
Source games later than Left 4 Dead 2 dont install. 

### ISSUE THREAD

**Issue by SquirrelKiev** [DarviL82/HAInstaller#3]
Seems to be an issue with CmdSeq.wc missing or being replaced in later source versions.

**Comment by SquirrelKiev** [comment]
turns out my hammer is just bugged?
it doesnt generate it until i open the run map dialogue. weird.

**Comment by darvil82** [comment]
Indeed. There was actually a warning saying "Make sure you opened hammer before" or something like that, but I ended up removing it.

**Comment by SquirrelKiev** [comment]
the weird part is the CmdSeq.wc file is missing the default configs. This isnt an issue with the installer or anything, just a strange hammer bug.
