### ISSUE TITLE
Installer says my steam directory is not valid because it's missing 1 file (uninstall.exe)

### ISSUE THREAD

**Issue by art0007i** [DarviL82/HAInstaller#4]
The installer tells me that 1 file is missing, after running this in verbose mode I was told that the missing file is uninstall.exe
I just created a new 0 byte file called uninstall.exe and the installer worked fine, I don't know why I don't have an uninstaller in my steam install but I don't think I removed it manually.

**Comment by darvil82** [comment]
That is weird... I will add an option to continue with the installation, even if its missing some files. I found some users that have different files, so I guess this is the best option.
