### ISSUE TITLE
Program gets stuck on 83% while downloading hammer addons.

### ISSUE THREAD

**Issue by lazyexcuse** [DarviL82/HAInstaller#6]
The Hammer Addons Extension freezes whenever it is at 83%, i think it happens every time when I download it for portal 2, I haven't tested this for other games yet.

**Comment by electrovoyage** [comment]
Have the same issue, have no idea what's wrong.

**Comment by electrovoyage** [comment]
Nevermind, unfroze after a few seconds.

**Comment by darvil82** [comment]
Closing this assuming it was a temporary network issue.
