### ISSUE TITLE
windows 7 compatibility?

### ISSUE THREAD

**Issue by thad4002** [DarviL82/HAInstaller#8]
![image](https://github.com/DarviL82/HAInstaller/assets/49796470/e72c8ea2-2c3f-4939-b9c5-18bd874e2f54)

**Comment by darvil82** [comment]
PyInstaller does no longer support Windows 7 as far as I'm aware, so there's a big chance it won't work correctly.
You may be able to run the python script manually, (note that you need the libraries listed in requirements.txt)
